name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: sushichan044/cli-gh-extension-precompile@fc00f51d32383d3b0e6a1e35d1f1fd22930f0cf9
        with:
          generate_attestations: true
          go_version_file: go.mod
          use_existing_draft: true
